package io.flowminer.api.enums;

public enum EnvironmentPhaseType {
    LAUNCH_BROWSER, PAGE_TO_HTML, EXTRACT_TEXT_FROM_ELEMENT, FILL_INPUT, CLICK_ELEMENT, DELIVER_VIA_WEBHOOK, EXTRACT_DATA_WITH_AI, READ_PROPERTY_FROM_JSON, ADD_PROPERTY_TO_JSON, NAVIGATE_URL, SCROLL_TO_ELEMENT
}
